# Generated by Django 6.0 on 2026-01-08 18:00

import api.models
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.comparison
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "muscle_group",
                    models.CharField(
                        choices=[
                            ("CHEST", "Chest"),
                            ("SHOULDER", "Shoulder"),
                            ("TRICEPS", "Triceps"),
                            ("BICEPS", "Biceps"),
                            ("BACK", "Back"),
                            ("QUAD", "Quad"),
                            ("HAMSTRING", "Hamstring"),
                            ("CALVE", "Calve"),
                            ("GLUTE", "Glute"),
                        ],
                        max_length=100,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("custom_type", models.BooleanField()),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MeasurementType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("unit", models.CharField(max_length=10)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="measurement_type_name_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("value", models.DecimalField(decimal_places=2, max_digits=6)),
                ("date", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "measurement_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.measurementtype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "birthdate",
                    models.DateField(validators=[api.models.validate_birthdate]),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(300),
                        ],
                    ),
                ),
                ("bio", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkoutLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("begintime", models.DateTimeField()),
                ("endtime", models.DateTimeField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExerciseLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exercise_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.exercisetype",
                    ),
                ),
                (
                    "workout_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_logs",
                        to="api.workoutlog",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExerciseSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reps",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(100)]
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(300),
                        ],
                    ),
                ),
                (
                    "rir",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(6)]
                    ),
                ),
                (
                    "exercise_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_sets",
                        to="api.exerciselog",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["exercise_log"], name="exercise_set_elog_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("reps__gte", 0)),
                        name="exerciseset_reps_gte_0",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("weight_kg__gte", 0)),
                        name="exerciseset_weight_kg_gte_0",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("rir__gte", 0)),
                        name="exerciseset_rir_gte_0",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="exercisetype",
            index=models.Index(fields=["name"], name="exercise_type_name_idx"),
        ),
        migrations.AddIndex(
            model_name="exercisetype",
            index=models.Index(
                fields=["muscle_group"], name="exercise_type_mgroup_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="exercisetype",
            constraint=models.UniqueConstraint(
                fields=("name", "user"), name="exercisetypeunique_user_exercise"
            ),
        ),
        migrations.AddIndex(
            model_name="measurement",
            index=models.Index(fields=["user"], name="measurement_user_idx"),
        ),
        migrations.AddIndex(
            model_name="measurement",
            index=models.Index(
                fields=["measurement_type"], name="measurement_mtype_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="measurement",
            index=models.Index(
                fields=["user", "measurement_type"],
                name="api_measure_user_id_791258_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="measurement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "date__lte",
                        django.db.models.functions.comparison.Cast(
                            django.db.models.functions.datetime.Now(),
                            output_field=models.DateField(),
                        ),
                    )
                ),
                name="measurement_date_not_in_future",
            ),
        ),
        migrations.AddConstraint(
            model_name="measurement",
            constraint=models.CheckConstraint(
                condition=models.Q(("value__gte", 0)), name="measurement_value_gte_0"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["user"], name="user_profile_user_idx"),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["created"], name="user_profile_created_idx"),
        ),
        migrations.AddConstraint(
            model_name="userprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("height__gte", 0)), name="userprofile_height_gte_0"
            ),
        ),
        migrations.AddIndex(
            model_name="workoutlog",
            index=models.Index(fields=["user"], name="workoutlog_user_idx"),
        ),
        migrations.AddIndex(
            model_name="workoutlog",
            index=models.Index(fields=["created"], name="workoutlog_created_idx"),
        ),
        migrations.AddConstraint(
            model_name="workoutlog",
            constraint=models.CheckConstraint(
                condition=models.Q(("begintime__lt", models.F("endtime"))),
                name="workoutlog_btime_before_endtime",
            ),
        ),
        migrations.AddIndex(
            model_name="exerciselog",
            index=models.Index(fields=["exercise_type"], name="exercise_log_etype_idx"),
        ),
        migrations.AddIndex(
            model_name="exerciselog",
            index=models.Index(fields=["workout_log"], name="exercise_log_wlog_idx"),
        ),
    ]
