# Generated by Django 6.0 on 2025-12-19 12:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_userprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="length",
            new_name="height",
        ),
        migrations.AlterField(
            model_name="measurementtype",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name="WorkoutLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("begintime", models.DateTimeField()),
                ("endtime", models.DateTimeField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExerciseLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exercise_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.exercisetype",
                    ),
                ),
                (
                    "workout_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="api.workoutlog",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExerciseSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reps", models.PositiveSmallIntegerField()),
                ("weight_kg", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "rpe",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "rir",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ]
                    ),
                ),
                (
                    "exercise_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="api.exerciselog",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["exercise_log"], name="api_exercis_exercis_d5e239_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="workoutlog",
            index=models.Index(
                fields=["user", "created"], name="api_workout_user_id_8ee2b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exerciselog",
            index=models.Index(
                fields=["workout_log"], name="api_exercis_workout_74af5b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="exerciselog",
            constraint=models.UniqueConstraint(
                fields=("workout_log", "exercise_type"),
                name="unique_exercise_per_workout",
            ),
        ),
    ]
